### ISSUE TITLE
Can miZy  run python and ssl client entirely from spi flash?

### ISSUE THREAD

**Issue by icodk** [hyphop/miZy#1]
@hyphop  For an IoT project, I am looking for a cheap hardware platform with Ethernet (wifi is optional) that can run a python script as a service and an SPI interface for reading sensors.
The python script should be able to read the sensors every second but post the data to an  https  server only when  sensor data was changed. max every 10-20 seconds.
Alternatively, the program could be written in C++.
The system should run as an embedded micro controller  running from spi flash without an sd
Can miZy and orange pi zero comply with those specs ?

Do you have other recommendations ?
Thanks in advance

**Comment by hyphop** [comment]
sure ! but u must pack all system in 8M or 16M spi flash! 
wait next week for binary mizy pre release
