### ISSUE TITLE
Please document OLED

### ISSUE THREAD

**Issue by probonopd** [hyphop/miZy#10]
* I am trying to use an 128x32 OLED instead of 128x64. What do I need to do?
* How can I make it display my own boot logo and messages?

**Comment by hyphop** [comment]
just correct connection to TWI0 (i2c SCK SDA) and GND +3.3V

**Comment by probonopd** [comment]
Yes, I have connected it and I see a picture, but I need 128x32 pixels instead of 128x64, and another picture in the early boot process. How do I do that? Thanks.

**Comment by hyphop** [comment]
ok 
check https://github.com/hyphop/miZy-uboot 
and this one 
https://github.com/hyphop/miZy-uboot/releases/download/v0.1-beta/u-boot-mizi.bin

logo injected in uboot it just uboot/i2c commands stored as uboot env + raw bit data stored by addr sm=XXXXXXXX ()
====================
if i2c dev 0 && i2c probe 3c; then
gpio set 6
# copy splash data to 0x43110000 addr
a=0x43110
cp.b $sm ${a}000 4096
# i2c commands block
i2c write ${a}000 3c 0 1A -s
i2c write ${a}01A 3c 0 7 -s
i2c write ${a}021 3c 0 401 -s
i2c write ${a}422 3c 0 401 -s
i2c write ${a}823 3c 0 8 -s
i2c write ${a}82B 3c 0 2 -s
echo "miZy splash"
fi

===

good luck

**Comment by probonopd** [comment]
Wow, you are a magician...

**Comment by hyphop** [comment]
please inform me about 128x32 display work
i can provide more helpful info if u need

**Comment by probonopd** [comment]
Thanks, I will let you know when I am working on it. For now I am trying to get [pjsua](http://www.pjsip.org/pjsua.htm) to run...
