### ISSUE TITLE
OrangePi R1 (RTL8189ETV wlan / RTL8152B ethernet)q

### ISSUE THREAD

**Issue by matthewbaggett** [hyphop/miZy#11]
For the life of me, I cannot work out how to build an environment where I can compile the drivers for these network devices.

miZy.linux.kernel.default.modules.full.tar.gz appears to contain a 8188eu.ko which I believe might support the 8189, as well as a rtl8150.ko for the rtl8152...

I'm so close to having a vpn appliance based upon your work working! I just need this blasted network connectivity to work! :stuck_out_tongue:

**Comment by hyphop** [comment]
i will try check it

**Comment by hyphop** [comment]
try to do this one before 
`eth1.on`

and check now
`ifconfig eth1`

**Comment by matthewbaggett** [comment]
```root@miZy:/etc/openvpn# eth1.on
sys: /opt/eth1.on
3: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 3e:fe:a7:e5:02:7b brd ff:ff:ff:ff:ff:ff
failed to find a module named cdc_ether
root@miZy:/etc/openvpn# ifconfig eth1
ifconfig: eth1: error fetching interface information: Device not found
```

Alas, no dice on my r1!

**Comment by hyphop** [comment]
OK ! we have rebuild image for R1 plz check it 
https://github.com/hyphop/miZy/releases/tag/R1

**Comment by hyphop** [comment]
OK
