### ISSUE TITLE
openwrt 

### ISSUE THREAD

**Issue by DRTEK** [hyphop/miZy#14]
hello 
do you have plans to make device packages for openwrt ? 
where can i find your boot scripts and other boot files ?
thanks

**Comment by hyphop** [comment]
about openwrt : packages still compatible  with mizy! but after last openwrt changes ! packages names and arch name changed - and not possible install it via opkg ! but possible install manually  

about boot script and other boot files location
https://github.com/hyphop/miZy/wiki/miZy-disk-partitions
