### ISSUE TITLE
wifi doesn't work on "python + wifi ap + wan dhcp eth + openvpn client + iptables + mobile"

### ISSUE THREAD

**Issue by geol** [hyphop/miZy#16]
I installed the lastest on MMC of my Orange Pi Zero, it works fantasy fast but the wifi seems not working. I connected to the wifi with my phone but just it can't connect to the Internet. By the way, how do I change some settings on miZy? I modify the "network" file on /etc/config/, but it can't be saved after a reboot command.

**Comment by hyphop** [comment]
1) i dont know why ) but wifi work fine ! - need more details
2) `overlay save -f` save permanent  changes 
3) https://github.com/hyphop/miZy/wiki - some mans / docs about mizy
