### ISSUE TITLE
not all changes to rc.local are kept

### ISSUE THREAD

**Issue by jgeisler0303** [hyphop/miZy#17]
Hi and thanks for this wonderful image!
I got it working and when I edit rc.local e.g. to comment out the launch of mpd and do `save_change` this is kept after the next reboot. But when I change `/opt/eth.disable` to `/opt/eth.on` this change seems to be magically be undone.
I would really like to enable wired Ethernet. Can you help me?

**Comment by jgeisler0303** [comment]
Hi, I solved the problem myself: there is no "magical" strange behavior. Instead, `save_changes` seems to not always write the changes to the SD card. Maybe there is some buffer and flushing this buffer is delayed. In any case, calling `save_changes`twice or even three time and/or waiting some time before reboot helped and all changes persisted.

**Comment by hyphop** [comment]
hi sorry for delayed answer ! its still actual ?



вт, 16 июл. 2019 г. в 21:26, Jens Geisler <notifications@github.com>:

**Comment by hyphop** [comment]
hi 
i have seen same issue but only with some sd cards ! may be its a cards problem?!
and never have same problem for spi flash! 

`overlay save -f ; sync` 

u can try exec  `sync` after save change but,  i have check `/opt/overlay` script and this have `sync` command already

plz confirm it for diff sd card and i will try to check this problem again!

**Comment by jgeisler0303** [comment]
Hi and thanks for the reply. The problem is still actual but almost never problematic anymore since I do the triple `save_changes` plus a `reboot`.
I will try you suggestions and observe different sd cards. But probably will not be gathering much intel soon since my device is now running headless as intended.

**Comment by hyphop** [comment]
never watch any problem for spi flash, only for some unbranded sd
