### ISSUE TITLE
HowTo Bluetooth

### ISSUE THREAD

**Issue by jgeisler0303** [hyphop/miZy#18]
Hi, is there any way I can add bluetooth to an image?

**Comment by hyphop** [comment]
sure its possible )

вс, 28 июл. 2019 г. в 23:02, Jens Geisler <notifications@github.com>:

**Comment by jgeisler0303** [comment]
I managed to get i running with automatic pairing via bluez-tools `bt-agent` tool.
I will soon write a summary for everybody interested about what I did.
I have now an image that can play audio via mpd, snapcast, bluetooth and usb. I call it AudioBeast and it runs in my active speakers.
Thanks so much for this great foundation that made it possible, especially the fast boot time, ro file system and working wifi.
I did try the option to boot from spi flash but that double the boot time, so I left the sd card in.

**Comment by hyphop** [comment]
tnx for good news ! you can provide this for free usage !

yes spi not so fast like sd! 
i think u khow we can boot from sd and remove it after, also we can use sd card for user storages just make proper partition offset for example **32784** if image size is 16M

```
master@peace:~$ echo $((2049*16*512))
16785408
master@peace:~$ echo $((2049*16))
32784
```

 ok wellcome !
close it
