### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by romankk** [hyphop/miZy#2]
Was trying to run 
`wget https://github.com/hyphop/miZy/releases/download/v0.1-beta/orange_pi_zero_miZy-music_box-mpd-net-SPI-beta_test.MMC.hybrid.16M.8192.bin.gz`

Getting 404

**Comment by hyphop** [comment]
hi

https://github.com/hyphop/miZy/releases

https://github.com/hyphop/miZy/releases/download/mpd/orange-pi-h2-miZy-musicbox-mpd.MMC.hybrid.16M.8192.bin.gz
