### ISSUE TITLE
OpenWRT

### ISSUE THREAD

**Issue by Spider84** [hyphop/miZy#4]
Hello!

Can you help me to run OpenWRT on Pi Zero from SPI?

**Comment by hyphop** [comment]
why not use miZy, its same openwrt based,
accept all openwrt packages ,

sure u can use mizy uboot  and repacked openwrt if u need boot from SPI

2018-02-26 18:34 GMT+07:00 Alexey Belyaev <notifications@github.com>:

**Comment by Spider84** [comment]
I want try to pack OpenWRT with needed for me packages for Pi Zero SPI.
Now I tried to undestand what I must change in OpenWRT kernel config to make it bootable from SPI.
As base I has take Orange Pi r1 config and you u-boot binnary.

In Orange Pi r1 kernel not enabled 25p80 driver, now I have enabled it but can't compile - many unresolved depends from u-boot :(

**Comment by hyphop** [comment]
if you don`t have qualification for it
better to use mizy and install all necessary openwrt packages
PS: mizy work fine on R1

**Comment by hyphop** [comment]
ok)
доводить до полной работоспособности openwrt на SPI для данных девайсов -
задача не востребованная - и к тому же требует много времени - чегоу меня
нет
- если кто готов профинансировать тогда можно обсудить -
вот я и ограничился только своей системой miZy - и только тем что мне от
нее нужно

я повторю что вся пакетная база openwrt подходит и для mizy

opkg update
opkg install ....

есть несколько нюансов но в целом miZy и openWrt достаточно близки

если вас интересует main line ядро - то мне оно сейчас не интересно - так
как не полностью поддерживает все что мне нужно от sunxi девайсов



28 февраля 2018 г., 11:56 пользователь Alexey Belyaev <
notifications@github.com> написал:

**Comment by Spider84** [comment]
Я вчера всё таки запустил OpenWrt из git на OPiZ, правда из под вашего u-boot, но со "своим" ядром и всем остальным. Возникло несколько вопросов:
1. А нет ли способа собирать dtb вместе с ядром в один файл? У роутеров на Реалтеках это же как то так.
2. можно ли грузить ядро сразу с SPI флеш, не читая его предварительно в память? Опять же роутеры это делают "нативно", но это я ещё изучаю.

**Comment by hyphop** [comment]
возможно - но мне это не было нужно - такчто пробуйте
