### ISSUE TITLE
Cannot install to SPI flash on Orange Pi Zero (H2+)

### ISSUE THREAD

**Issue by probonopd** [hyphop/miZy#6]
Currently it seems like one needs a serial adapter to get this to work, because the device does not come up as a DHCP client on Ethernet automatically.

Installed miZy according to https://github.com/hyphop/miZy/wiki/miZy-download-install-overlay-usage:

* With [Etcher](https://etcher.io/), burned `orange-pi-h2-miZy-musicbox-mpd.MMC.hybrid.8M.8192.bin` to SD card
* Booted Orange Pi Zero from SD
* Attached serial adapter as shown [here](https://sigmdel.ca/michel/ha/opi/OPiZ_uart_en.html)
* `sudo screen /dev/ttyUSB0 115200`

Trying to copy system to SPI

```
root@miZy:/# image_copy_sd_spi yes
cat: can't open '/sys/block/mmcblk1/device/type': No such file or directory
[i] sd /dev/mmcblk0 mmc 
[e] not found block dev /dev/mtdblock
```

__Fails__, is it missing some mtd devices?

```
root@miZy:/# ls /dev/mtdblock*
/dev/mtdblock0  /dev/mtdblock1  /dev/mtdblock2
```

The SPI flash chip is installed on the board from the factory.

**Comment by probonopd** [comment]
Similar message when using `orange_pi_zero_miZy-mini-turbo.MMC.hybrid.8M.8192.bin` instead:

```
root@miZy:/# image_copy_sd_spi yes
cat: can't open '/sys/block/mmcblk1/device/type': No such file or directory
[i] sd /dev/mmcblk0 mmc 
[e] not found block dev /dev/mtdblock
```

**Comment by probonopd** [comment]
Note to self: Use `flashrom` to identify the chip.

**Comment by hyphop** [comment]
pls check



*spi_flash_info *for example i have

root@miZy:~# spi_flash_info
SPI bus /sys/devices/platform/spi*
DEV dev /sys/devices/platform/spi*/spi_master/spi*/spi*
DRIVER=m25p80
MODALIAS=spi:W25q128
MODALIAS=spi:mmc_spi
FLASH CHIP: W25q128
mmc_spi

and  another



*spi_flash_dmesg*root@miZy:~# spi_flash_dmesg
[    0.000000] Kernel command line: ramdisk_size=8192 mmc_core.removable=1
hdmi.audio=EDID:0 threadirqs  itype=openwrt root=/dev/ram0 rw console=tty1
console=ttyS0,115200
mtdparts=W25q128-flash.0:512k(uboot),64k(script),64k(dtb),2432k(kernel),6976k(initrd),6336k(user),-@0(full)
panic=10 consoleblank=0 loglevel=3 sunxi_ve_mem_reserve=0
sunxi_g2d_mem_reserve=0 sunxi_fb_mem_reserve=16 bootfrom=sd loadfrom=MMC0
loadseq=>MMC0
mmcparts=uboot=524288;script=65536;dtb=65536;kernel=2490368;initrd=7143424;user=6488064
btime=3.626
[    0.387495] spi spi0: master is unqueued, this is deprecated
[    0.388021] NorFlash ID: 0xef4018 - 0x0
[    0.388065] m25p80 spi0.0: W25q128 (16384 Kbytes)
[    0.388172] 0x000000000000-0x000000080000 : "uboot"
[    2.243442] block2mtd: mtd7: [/dev/loop0] erase_size = 64KiB [65536]
[    3.791810] block2mtd: mtd7: [/dev/loop0] removed

if u dont have same try to change  fex config

root@miZy:~# fex_dump | grep -A8 spi_board0
fexc-bin: <stdin>: version: 1.2
fexc-bin: <stdin>: size: 131072 (85 sections), header value: 35048
[spi_board0]







*modalias = "W25q128"max_speed_hz = 36000000mode = 0bus_num = 0chip_select
= 0full_duplex = 1manual_cs = 0*

fex_edit

good luck)

2018-03-17 17:47 GMT+07:00 probonopd <notifications@github.com>:

**Comment by hyphop** [comment]
default macronix spi flash (orange pi zero) its just 2M 
is small for miZy 
miZy - 8M is minimum 

replace to any up 8M

**Comment by probonopd** [comment]
> default macronix spi flash (orange pi zero) its just 2M
> is small for miZy
> miZy - 8M is minimum
> 
> replace to any up 8M

Thank you. I fear that I will blow off all the small capacitors with the hot air gun ;-)

**Comment by hyphop** [comment]
remove spi flash its very easy and no need hot-air gun - just solder gun +
pin

2018-03-18 0:14 GMT+07:00 probonopd <notifications@github.com>:

**Comment by hyphop** [comment]
or cut by blade every pin one by one
its more easy

2018-03-20 8:10 GMT+07:00 Artem AiRadio <ai.radio.org@gmail.com>:
