### ISSUE TITLE
Invalid http://usbhost entries

### ISSUE THREAD

**Issue by probonopd** [hyphop/miZy#7]
Is this intentional? 

```
Downloading http://usbhost/sunxi/packages/base/Packages.
wget: can't connect to remote host (10.1.1.2): Host is unreachable
Downloading http://usbhost/sunxi/packages/packages/Packages.
wget: can't connect to remote host (10.1.1.2): Host is unreachable
Downloading http://usbhost/sunxi/packages/mizy/Packages.
wget: can't connect to remote host (10.1.1.2): Host is unreachable
Collected errors:
 * opkg_download: Failed to download http://usbhost/sunxi/packages/base/Packages, wget returned 1.
 * opkg_download: Failed to download http://usbhost/sunxi/packages/packages/Packages, wget returned 1.
 * opkg_download: Failed to download http://usbhost/sunxi/packages/mizy/Packages, wget returned 1.
```

**Comment by hyphop** [comment]
root@miZy:~# grep http /etc/opkg/*.conf 
/etc/opkg/customfeeds.conf:# src/gz example_feed_name http://www.example.com/path/to/files
/etc/opkg/distfeeds.conf:src/gz designated_driver_base http://downloads.openwrt.org/snapshots/trunk/sunxi/generic/packages/base
/etc/opkg/distfeeds.conf:src/gz designated_driver_packages http://downloads.openwrt.org/snapshots/trunk/sunxi/generic/packages/packages
/etc/opkg/local.conf:src local_openwrt_base     http://usbhost/sunxi/packages/base
/etc/opkg/local.conf:src local_openwrt_packages http://usbhost/sunxi/packages/packages
/etc/opkg/local.mizy.conf:src local_mizy http://usbhost/sunxi/packages/mizy

u can change to any source

usbhost work only via usb_otg

**Comment by probonopd** [comment]
> usbhost work only via usb_otg

Thanks for the hint.
