### ISSUE TITLE
Russian in wiki

### ISSUE THREAD

**Issue by probonopd** [hyphop/miZy#9]
Hello, I am trying to learn how to use miZy. I notice that some parts of the documentation in the wiki are in Russian while others are in English. Is this intentional? Would you like me to translate it to English?

**Comment by hyphop** [comment]
sure) but i have problem with free time now !
and make some documentation or manuals by request

**Comment by probonopd** [comment]
Please make the wiki editable if you'd like me to translate it into English. (I also might add some documentation while I am discovering miZy.) Keep up your great work!

**Comment by orangepi0** [comment]
ok! wiki write permissions is activated for everybody
